#!/usr/bin/env python3
"""
Update _data/training_data.yml with the rolling 7-day training window.

Run daily via Cowork:
  cd /Users/fabriziogiovanninifilho/Documents/fabriziogf_page
  /Users/fabriziogiovanninifilho/ai-projects/trainingpeaks-mcp/.venv/bin/python3 scripts/update_training_data.py

The script fetches yesterday's completed window (yesterday - 6 days → yesterday),
writes _data/training_data.yml, then commits and pushes.
"""

import asyncio
import sys
import os
from datetime import date, timedelta
from pathlib import Path

# Add TrainingPeaks MCP to path
TP_MCP = Path("/Users/fabriziogiovanninifilho/ai-projects/trainingpeaks-mcp")
sys.path.insert(0, str(TP_MCP / "src"))

from tp_mcp.tools.workouts import tp_get_workouts
from tp_mcp.tools.fitness import tp_get_fitness

REPO = Path(__file__).parent.parent
OUT  = REPO / "_data" / "training_data.yml"

# ── Sport classifier ────────────────────────────────────────────────────────
SWIM_KEYS = [
    'swim', 'lap swimming', 'a1', 'a2', 'a3', 'natação', 'paraquedas',
    'crawl', '150m', '200m', '400m', '1200m', '2000m', '3000m',
    'lipolítico', 'melhor média', 'progressivo a1', 'equipamento',
]
BIKE_KEYS = [
    'zwift', 'cycling', 'ciclismo', 'pedal', 'bloco', 'road cycling',
    'z2', 'z3', 'z4', 'zona 2', 'zona 3', 'zona 4', 'easy miles',
    'big gear', 'girando', 'giro', 'sessão l2', 'l2/z4',
    'circuito misto', 'volume 5', '5 horas',
]
RUN_KEYS = [
    'corrida', 'running', 'corridinha', 'fartlek', 'ritmo',
    'progressivo entre', 'progressão', 'esforço', 'muito fácil',
    'após a bike', 'após final', 'após o ciclismo', 't2', 'brick',
]
STR_TITLES = {
    'Strength', 'Treino A - BASE', 'Treino B - BASE',
    'Treino B - Base', 'Base - Serie A',
}

def classify(title: str) -> str:
    if title in STR_TITLES or 'strength' in (title or '').lower():
        return 'strength'
    t = (title or '').lower()
    if any(k in t for k in SWIM_KEYS): return 'swim'
    if any(k in t for k in RUN_KEYS):  return 'run'
    if any(k in t for k in BIKE_KEYS): return 'bike'
    return 'other'


# ── YAML writer (no external deps) ─────────────────────────────────────────
def q(s):
    """Quote a string for YAML."""
    return f'"{s}"'

def build_yaml(data: dict) -> str:
    td = data
    lines = [
        "# Auto-generated by scripts/update_training_data.py",
        "# Do not edit manually — overwritten daily by the Cowork job.",
        "",
        f"generated_at: {q(td['generated_at'])}",
        f"window_start: {q(td['window_start'])}",
        f"window_end:   {q(td['window_end'])}",
        "",
        "fitness:",
        f"  ctl:  {td['fitness']['ctl']}",
        f"  atl:  {td['fitness']['atl']}",
        f"  tsb:  {td['fitness']['tsb']}",
        "",
        "totals:",
    ]
    sports = ['swim', 'bike', 'run', 'strength', 'other']
    for s in sports:
        t = td['totals'][s]
        lines += [
            f"  {s}:",
            f"    sessions:    {t['sessions']}",
            f"    hours:       {t['hours']}",
            f"    distance_km: {t['distance_km']}",
            f"    tss:         {t['tss']}",
        ]
    lines += ["", "daily:"]
    for d in td['daily']:
        lines.append(f"  - date: {q(d['date'])}")
        for s in sports:
            v = d[s]
            lines.append(
                f"    {s:<8}: "
                f"{{ hours: {v['hours']:<5}, distance_km: {v['distance_km']:<6}, "
                f"tss: {v['tss']:<6}, sessions: {v['sessions']} }}"
            )
    lines += ["", "workouts:"]
    for w in td['workouts']:
        dist_str = str(w['distance_km'])
        lines.append(
            f"  - {{ date: {q(w['date'])}, sport: {w['sport']:<8}, "
            f"title: {q(w['title'])}, "
            f"hours: {w['hours']}, distance_km: {dist_str}, tss: {w['tss']} }}"
        )
    lines.append("")
    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────
async def main():
    today = date.today()
    end   = today - timedelta(days=1)   # yesterday = last complete day
    start = end - timedelta(days=6)     # 7-day window

    print(f"Fetching {start} → {end} …")
    workouts_res, fitness_res = await asyncio.gather(
        tp_get_workouts(start.isoformat(), end.isoformat(), 'completed'),
        tp_get_fitness(start_date=start.isoformat(), end_date=end.isoformat()),
    )
    workouts     = workouts_res.get('workouts', [])
    daily_fitness = {d['date']: d for d in fitness_res.get('daily_data', [])}

    totals = {s: {'sessions': 0, 'hours': 0.0, 'distance_km': 0.0, 'tss': 0.0}
              for s in ['swim', 'bike', 'run', 'strength', 'other']}
    days = {}
    for i in range(7):
        d = (start + timedelta(days=i)).isoformat()
        days[d] = {s: {'hours': 0.0, 'distance_km': 0.0, 'tss': 0.0, 'sessions': 0}
                   for s in ['swim', 'bike', 'run', 'strength', 'other']}

    workout_list = []
    for w in workouts:
        sport = classify(w['title'])
        tss   = round(w.get('tss') or 0, 1)
        hrs   = round(w.get('duration_actual') or 0, 2)
        dist  = round(w.get('distance_actual_km') or 0, 1)
        totals[sport]['sessions']    += 1
        totals[sport]['hours']       += hrs
        totals[sport]['distance_km'] += dist
        totals[sport]['tss']         += tss
        if w['date'] in days:
            days[w['date']][sport]['hours']       += hrs
            days[w['date']][sport]['distance_km'] += dist
            days[w['date']][sport]['tss']         += tss
            days[w['date']][sport]['sessions']    += 1
        workout_list.append({
            'date': w['date'], 'title': w['title'], 'sport': sport,
            'hours': hrs, 'distance_km': dist, 'tss': tss,
        })

    for s in totals:
        totals[s]['hours']       = round(totals[s]['hours'], 1)
        totals[s]['distance_km'] = round(totals[s]['distance_km'], 1)
        totals[s]['tss']         = int(round(totals[s]['tss'], 0))

    last_fitness = {'ctl': 0.0, 'atl': 0.0, 'tsb': 0.0}
    if daily_fitness:
        last = sorted(daily_fitness.keys())[-1]
        fd = daily_fitness[last]
        last_fitness = {
            'ctl': fd.get('ctl', 0.0),
            'atl': fd.get('atl', 0.0),
            'tsb': fd.get('tsb', 0.0),
        }

    daily_list = []
    for d in sorted(days.keys()):
        entry = {'date': d}
        for s in ['swim', 'bike', 'run', 'strength', 'other']:
            entry[s] = {k: round(v, 1) for k, v in days[d][s].items()}
        daily_list.append(entry)

    data = {
        'generated_at': today.isoformat(),
        'window_start': start.isoformat(),
        'window_end':   end.isoformat(),
        'fitness':      last_fitness,
        'totals':       totals,
        'daily':        daily_list,
        'workouts':     workout_list,
    }

    OUT.write_text(build_yaml(data), encoding='utf-8')
    print(f"Written → {OUT}")

    # Commit and push
    os.chdir(REPO)
    os.system(f'git add _data/training_data.yml')
    os.system(f'git commit -m "chore: update training dashboard [{today}]"')
    os.system('git push origin main')
    print("Pushed.")


if __name__ == "__main__":
    asyncio.run(main())
