#!/usr/bin/env python3
"""
Update _data/training_data.yml with the rolling 7-day training window.

Run daily via Cowork:
  cd /Users/fabriziogiovanninifilho/Documents/fabriziogf_page
  /Users/fabriziogiovanninifilho/ai-projects/trainingpeaks-mcp/.venv/bin/python3 scripts/update_training_data.py

The script fetches yesterday's completed window (yesterday - 6 days → yesterday),
writes _data/training_data.yml, then commits and pushes.
"""

import asyncio
import sys
import os
from datetime import date, timedelta
from pathlib import Path

# Add TrainingPeaks MCP to path
TP_MCP = Path("/Users/fabriziogiovanninifilho/ai-projects/trainingpeaks-mcp")
sys.path.insert(0, str(TP_MCP / "src"))

from tp_mcp.tools.fitness import tp_get_fitness
from tp_mcp.client import TPClient

REPO = Path(__file__).parent.parent
OUT  = REPO / "_data" / "training_data.yml"

# ── Sport classifier using workoutTypeValueId (authoritative TP field) ──────
# Mirrors SPORT_TYPE_MAP in tp_mcp/tools/workouts.py
TYPE_ID_TO_SPORT: dict[int, str] = {
    1:   'swim',
    2:   'bike',
    3:   'run',
    4:   'bike',      # Brick — primary discipline is bike
    5:   'other',     # Crosstrain
    6:   'other',     # Race
    7:   'other',     # Day Off
    8:   'bike',      # MtnBike
    9:   'strength',  # Strength
    10:  'other',     # Custom
    11:  'other',     # XCSki
    12:  'other',     # Rowing
    13:  'run',       # Walk
    100: 'other',     # Other
}

def classify(type_id: int | None) -> str:
    return TYPE_ID_TO_SPORT.get(type_id, 'other')


# ── YAML writer (no external deps) ─────────────────────────────────────────
def q(s):
    """Quote a string for YAML."""
    return f'"{s}"'

def build_yaml(data: dict) -> str:
    td = data
    lines = [
        "# Auto-generated by scripts/update_training_data.py",
        "# Do not edit manually — overwritten daily by the Cowork job.",
        "",
        f"generated_at: {q(td['generated_at'])}",
        f"window_start: {q(td['window_start'])}",
        f"window_end:   {q(td['window_end'])}",
        "",
        "fitness:",
        f"  ctl:  {td['fitness']['ctl']}",
        f"  atl:  {td['fitness']['atl']}",
        f"  tsb:  {td['fitness']['tsb']}",
        "",
        "totals:",
    ]
    sports = ['swim', 'bike', 'run', 'strength', 'other']
    for s in sports:
        t = td['totals'][s]
        lines += [
            f"  {s}:",
            f"    sessions:    {t['sessions']}",
            f"    hours:       {t['hours']}",
            f"    distance_km: {t['distance_km']}",
            f"    tss:         {t['tss']}",
        ]
    lines += ["", "daily:"]
    for d in td['daily']:
        lines.append(f"  - date: {q(d['date'])}")
        for s in sports:
            v = d[s]
            lines.append(
                f"    {s:<8}: "
                f"{{ hours: {v['hours']:<5}, distance_km: {v['distance_km']:<6}, "
                f"tss: {v['tss']:<6}, sessions: {v['sessions']} }}"
            )
    lines += ["", "workouts:"]
    for w in td['workouts']:
        dist_str = str(w['distance_km'])
        lines.append(
            f"  - {{ date: {q(w['date'])}, sport: {w['sport']:<8}, "
            f"title: {q(w['title'])}, "
            f"hours: {w['hours']}, distance_km: {dist_str}, tss: {w['tss']} }}"
        )
    lines.append("")
    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────
async def main():
    today = date.today()
    end   = today - timedelta(days=1)   # yesterday = last complete day
    start = end - timedelta(days=6)     # 7-day window

    print(f"Fetching {start} → {end} …")

    # Fetch raw workouts directly so we have workoutTypeValueId
    async with TPClient() as client:
        athlete_id = await client.ensure_athlete_id()
        endpoint   = f"/fitness/v6/athletes/{athlete_id}/workouts/{start}/{end}"
        raw_resp   = await client.get(endpoint)
    raw_workouts = [
        w for w in (raw_resp.data or [])
        if w.get('totalTime') or w.get('tssActual')   # completed only
    ]

    fitness_res   = await tp_get_fitness(start_date=start.isoformat(), end_date=end.isoformat())
    daily_fitness = {d['date']: d for d in fitness_res.get('daily_data', [])}

    totals = {s: {'sessions': 0, 'hours': 0.0, 'distance_km': 0.0, 'tss': 0.0}
              for s in ['swim', 'bike', 'run', 'strength', 'other']}
    days = {}
    for i in range(7):
        d = (start + timedelta(days=i)).isoformat()
        days[d] = {s: {'hours': 0.0, 'distance_km': 0.0, 'tss': 0.0, 'sessions': 0}
                   for s in ['swim', 'bike', 'run', 'strength', 'other']}

    workout_list = []
    for w in raw_workouts:
        sport = classify(w.get('workoutTypeValueId'))
        # Normalize fields from raw API shape
        w = {
            'date':             (w.get('workoutDay') or '')[:10],
            'title':            w.get('title', ''),
            'tss':              w.get('tssActual'),
            'duration_actual':  w.get('totalTime'),
            'distance_actual_km': (w.get('distance') or 0) / 1000,
        }
        tss   = round(w.get('tss') or 0, 1)
        hrs   = round(w.get('duration_actual') or 0, 2)
        dist  = round(w.get('distance_actual_km') or 0, 1)
        totals[sport]['sessions']    += 1
        totals[sport]['hours']       += hrs
        totals[sport]['distance_km'] += dist
        totals[sport]['tss']         += tss
        if w['date'] in days:
            days[w['date']][sport]['hours']       += hrs
            days[w['date']][sport]['distance_km'] += dist
            days[w['date']][sport]['tss']         += tss
            days[w['date']][sport]['sessions']    += 1
        workout_list.append({
            'date': w['date'], 'title': w['title'], 'sport': sport,
            'hours': hrs, 'distance_km': dist, 'tss': tss,
        })

    for s in totals:
        totals[s]['hours']       = round(totals[s]['hours'], 1)
        totals[s]['distance_km'] = round(totals[s]['distance_km'], 1)
        totals[s]['tss']         = int(round(totals[s]['tss'], 0))

    last_fitness = {'ctl': 0.0, 'atl': 0.0, 'tsb': 0.0}
    if daily_fitness:
        last = sorted(daily_fitness.keys())[-1]
        fd = daily_fitness[last]
        last_fitness = {
            'ctl': fd.get('ctl', 0.0),
            'atl': fd.get('atl', 0.0),
            'tsb': fd.get('tsb', 0.0),
        }

    daily_list = []
    for d in sorted(days.keys()):
        entry = {'date': d}
        for s in ['swim', 'bike', 'run', 'strength', 'other']:
            entry[s] = {k: round(v, 1) for k, v in days[d][s].items()}
        daily_list.append(entry)

    data = {
        'generated_at': today.isoformat(),
        'window_start': start.isoformat(),
        'window_end':   end.isoformat(),
        'fitness':      last_fitness,
        'totals':       totals,
        'daily':        daily_list,
        'workouts':     workout_list,
    }

    OUT.write_text(build_yaml(data), encoding='utf-8')
    print(f"Written → {OUT}")

    # Commit and push
    os.chdir(REPO)
    os.system(f'git add _data/training_data.yml')
    os.system(f'git commit -m "chore: update training dashboard [{today}]"')
    os.system('git push origin main')
    print("Pushed.")


if __name__ == "__main__":
    asyncio.run(main())
